import {
  GET_GOALS_REQUEST,
  GET_GOALS_SUCCESS,
  GET_GOALS_FAILURE,
  getAllGoals,
} from './goal';

import {
  GET_TARGETS_REQUEST,
  GET_TARGETS_SUCCESS,
  GET_TARGETS_FAILURE,
  getAllTargets,
} from './target';

export {
  GET_GOALS_REQUEST,
  GET_GOALS_SUCCESS,
  GET_GOALS_FAILURE,
  getAllGoals,
  GET_TARGETS_REQUEST,
  GET_TARGETS_SUCCESS,
  GET_TARGETS_FAILURE,
  getAllTargets,
};
